### PR TITLE
Speed up installer on large home directories

### LINKED ISSUE #91: Endless loop when glob() encounters a symlink loop
I'm currently trying to install Logos using this repo, after having tried (and failing) to use https://github.com/ferion11/LogosLinuxInstaller .
Now it seems that the installer goes into an endless loop, because the files listed inside `~/LogosBible10/data/wine64_bottle` (which I still have around from previous installs) contains symlink loops.
One of the culprits seem to be:
```
thomas@bluelight:~/LogosBible10/data/wine64_bottle/drive_c/users/thomas/AppData/Roaming/Microsoft/Windows$ ls -l Templates
lrwxrwxrwx 1 thomas thomas 13 Apr 13 08:42 Templates -> /home/thomas/
```
But the install contained several symlink loops. The backtrace looks like this:
```
Traceback (most recent call last):
  File "/home/thomas/coding/LogosLinuxInstaller-FaithLife/./LogosLinuxInstaller.py", line 340, in <module>
    main()
  File "/home/thomas/coding/LogosLinuxInstaller-FaithLife/./LogosLinuxInstaller.py", line 336, in main
    run_control_panel()
  File "/home/thomas/coding/LogosLinuxInstaller-FaithLife/./LogosLinuxInstaller.py", line 251, in run_control_panel
    tui_app.control_panel_app()
  File "/home/thomas/coding/LogosLinuxInstaller-FaithLife/tui_app.py", line 83, in control_panel_app
    installer.install()
  File "/home/thomas/coding/LogosLinuxInstaller-FaithLife/installer.py", line 519, in install
    finish_install()
  File "/home/thomas/coding/LogosLinuxInstaller-FaithLife/installer.py", line 537, in finish_install
    if check_existing_install(app):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomas/coding/LogosLinuxInstaller-FaithLife/installer.py", line 191, in check_existing_install
    if os.path.isdir(drive_c) and any(glob.glob(f"{drive_c}/**/{n}", recursive=True) for n in names):  # noqa: E501
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomas/coding/LogosLinuxInstaller-FaithLife/installer.py", line 191, in <genexpr>
    if os.path.isdir(drive_c) and any(glob.glob(f"{drive_c}/**/{n}", recursive=True) for n in names):  # noqa: E501
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lib/python3.12/glob.py", line 28, in glob
    return list(iglob(pathname, root_dir=root_dir, dir_fd=dir_fd, recursive=recursive,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lib/python3.12/glob.py", line 96, in _iglob
    for dirname in dirs:
  File "/opt/lib/python3.12/glob.py", line 97, in _iglob
    for name in glob_in_dir(_join(root_dir, dirname), basename, dir_fd, dironly,
  File "/opt/lib/python3.12/glob.py", line 136, in _glob2
    yield from _rlistdir(dirname, dir_fd, dironly,
  File "/opt/lib/python3.12/glob.py", line 186, in _rlistdir
    for y in _rlistdir(path, dir_fd, dironly,
  File "/opt/lib/python3.12/glob.py", line 186, in _rlistdir
    for y in _rlistdir(path, dir_fd, dironly,
  File "/opt/lib/python3.12/glob.py", line 186, in _rlistdir
    for y in _rlistdir(path, dir_fd, dironly,
  [Previous line repeated 14 more times]
  File "/opt/lib/python3.12/glob.py", line 188, in _rlistdir
    yield _join(x, y)
          ^^^^^^^^^^^
  File "/opt/lib/python3.12/glob.py", line 217, in _join
    return os.path.join(dirname, basename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 85, in join
KeyboardInterrupt
```

I think globbing should not follow symlinks, but I have not checked if this is easily possible.

### PR DESCRIPTION
**Pull request by tbleher**
glob.glob would take *very* long, since it follows symlinks, and the wine installation contains several symlink loops and also has links both to the home directory and to /. Use os.walk instead to greatly reduce the installer time.

Fixes #91

### CODE REVIEW

**Comment by tbleher** [comment]
This fixes the issue for me that I reported in #91. I'm not an experienced Python programmer, so I'm open to suggestions how to solve this in a more Pythonic way :)

**Comment by thw26** [comment]
Thank you for the contribution!

I don't see an issue with this code, though I haven't tested.

This has been more in @n8marti's area and I will defer to him on this.

**Comment by n8marti** [comment]
Thanks for your research, @tbleher. I've done some testing, and I see that  `glob.glob` is definitely a very slow choice. It necessarily examines the entire subtree beneath the `drive_c` starting point. Like you say, the bigger the subtree the greater the glob search. And since the goal in both cases where `glob.glob` is used is to return a single file path, a full subtree search unnecessarily continues execution, even after the desired path is found. My testing confirms that walking the subtree and returning the first matching file path is definitely a much faster route. Thanks for the tip!

I'm also trying to make use of pathlib.Path wherever possible, and my testing also found that using `Path.walk()` produces an even faster result, taking about 75% as long as `os.walk()` (and 8% as long as `glob.glob` and 33% as long as `Path.rglob`). I tested 100 iterations of each method on my snap installation, which includes symlinks to all my resources, which are stored outside of the wine filesystem:
```
$ python test/glob_vs_walk.py ~/snap/logos10-unofficial/common/.wine/drive_c/
path_walk       0.8947485160024371
os_walk         1.2930735099944286
path_rglob1     2.7966266720031854
path_rglob2     2.3447233049955685
glob_glob       11.96943177099456
```
Here's the gist of how `Path.walk()` could be integrated into `installer.py` in the `finish_install` function:
```python
for root, _, files in Path(f"{config.WINEPREFIX}/drive_c/").walk(follow_symlinks=False):
    if root.name == config.FLPRODUCT and f"{config.FLPRODUCT}.exe" in files:
        config.LOGOS_EXE = root / f"{config.FLPRODUCT}.exe"
        break
if not config.LOGOS_EXE:
    msg.logos_error("Logos was not installed.")
```
However, we're actually reworking the `installer` module, which will eliminate the need for the first use of `glob.glob`. And the 2nd use of it will be found in the new function [`utils.find_installed_product()`](https://github.com/FaithLife-Community/LogosLinuxInstaller/blob/ab8c73eb81f651f9f52faacbeb5b2d724e5b034a/utils.py#L1156).

If you'd like your contribution to officially come from you, I suggest you make a new PR against the `alt-installer` branch and modify `utils.find_installed_product()` accordingly. Otherwise, I can work it in myself, but that would prevent you from getting "GitHub kudos" for the contribution.

**Comment by tbleher** [comment]
Thanks @n8marti for the quick review! I don't care that much about "GitHub kudos" :)
I guess you're faster than me in integrating the code into the proper branch, and I will will rather take the time to look a bit more deeply into wine, to see if I can improve compatibility with Logos (though I can't promise anything there, since this is probably a quite large topic).

**Comment by n8marti** [comment]
This recommendation has been integrated in with [053dd36](https://github.com/FaithLife-Community/LogosLinuxInstaller/pull/85/commits/053dd36d100bc7d14ba706d8323ea91944b839ac)

**Pull request closed without merging**
