### PR TITLE
Fix self-update download

### LINKED ISSUE #97: Self-update might result in broken binary
It seems like `utils.update_lli_binary` and `utils.logos_reuse_download` might be resulting in a broken LLI binary. If the current version is smaller than the latest version, and the current version's binary is in the user's Downloads folder, then `logos_reuse_download`, via `utils.net_get`, will "resume" the download. This results in the correct file size, but the wrong checksum. A `CRITICAL` error is logged, but `update_lli_binary` continues. So it seems that the broken binary replaces the running binary.

At least one user sees their X session crash when this happens. How or why would that happen?

I will look into whether it makes the most sense to have `update_lli_binary` or `logos_reuse_download` restart the download if the checksum is bad. In the meantime, the user might avoid the problem by removing `~/Downloads/LogosLinuxInstaller` before attempting to run the self-update.

### PR DESCRIPTION
**Pull request by n8marti**
- Fix #97: Check downloaded LogosLinuxInstaller binary for version number. Remove if not latest version before attempting to download & install latest version. 
- Fix download progress bar for LLI self-update in GUI
- Simplify GUI's download and integrity check code
- Show LLI version number next to Control Panel title (TUI & GUI):
image
image

### CODE REVIEW

**Review by thw26 — COMMENTED** [review]
The TUI worked fine but in the GUI I'm now seeing this error:

```
(LogosLinuxInstaller) 20:15:14 [thwright@thw-g752vlw ~/Dev/LogosLinuxInstaller] LLI_CURRENT_VERSION=4.0.0-alpha.3 DIALOG=curses ./dist/LogosLinuxInstaller 
(LogosLinuxInstaller) 20:15:24 [thwright@thw-g752vlw ~/Dev/LogosLinuxInstaller] cp ~/.config/Logos_on_Linux/Logos_on_Linux.json.bak ~/.config/Logos_on_Linux/Logos_on_Linux.json
cp: overwrite '/home/thwright/.config/Logos_on_Linux/Logos_on_Linux.json'? y
(LogosLinuxInstaller) 20:15:33 [thwright@thw-g752vlw ~/Dev/LogosLinuxInstaller] LLI_CURRENT_VERSION=4.0.0-alpha.3 DIALOG=curses ./dist/LogosLinuxInstaller 
Downloading 'https://github.com/FaithLife-Community/LogosLinuxInstaller/releases/download/v4.0.0-alpha.6/LogosLinuxInstaller' to '/home/thwright/Downloads/LogosLinuxInstaller'
 [............................................................] 100%
Copying: LogosLinuxInstaller into: /home/thwright/Downloads
(LogosLinuxInstaller) 20:16:08 [thwright@thw-g752vlw ~/Dev/LogosLinuxInstaller] ~/Downloads/LogosLinuxInstaller -v
bash: /home/thwright/Downloads/LogosLinuxInstaller: Permission denied
(LogosLinuxInstaller) 20:16:19 [thwright@thw-g752vlw ~/Dev/LogosLinuxInstaller] chmod 700 ~/Downloads/LogosLinuxInstaller
(LogosLinuxInstaller) 20:16:27 [thwright@thw-g752vlw ~/Dev/LogosLinuxInstaller] ~/Downloads/LogosLinuxInstaller -v
Logos Linux Installer, 4.0.0-alpha.6 by Ferion11, John Goodman, T. H. Wright, N. Marti
(LogosLinuxInstaller) 20:16:29 [thwright@thw-g752vlw ~/Dev/LogosLinuxInstaller] LLI_CURRENT_VERSION=4.0.0-alpha.3 DIALOG=tk ./dist/LogosLinuxInstaller 
2024-04-24 20:16:52 ERROR: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Copying LogosLinuxInstaller into /home/thwright/Downloads
2024-04-24 20:17:08 ERROR: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Copying LogosLinuxInstaller into /home/thwright/Downloads
Exception in thread Thread-1 (get_app_logging_state):
Traceback (most recent call last):
  File "threading.py", line 1073, in _bootstrap_inner
  File "threading.py", line 1010, in run
  File "wine.py", line 303, in get_app_logging_state
    app.root.event_generate('<<InitLoggingButton>>')
  File "tkinter/__init__.py", line 1933, in event_generate
RuntimeError: main thread is not in main loop
(LogosLinuxInstaller) 20:17:13 [thwright@thw-g752vlw ~/Dev/LogosLinuxInstaller] LLI_CURRENT_VERSION=4.0.0-alpha.5 DIALOG=tk ./dist/LogosLinuxInstaller 
2024-04-24 20:17:30 ERROR: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Copying LogosLinuxInstaller into /home/thwright/Downloads
```

The only thing I can think is that the binary version in ~/Downloads is now a.6.

So I moved another binary I had into place. I ran the update and got the following.

```
(LogosLinuxInstaller) 20:18:45 [thwright@thw-g752vlw ~/Dev/LogosLinuxInstaller] ~/Downloads/LogosLinuxInstaller\(1\) -v
Logos Linux Installer, 4.0.0-alpha.1 by Ferion11, John Goodman, T. H. Wright, N. Marti
Logos Linux Installer, 4.0.0-alpha.1 by Ferion11, John Goodman, T. H. Wright, N. Marti
(LogosLinuxInstaller) 20:18:51 [thwright@thw-g752vlw ~/Dev/LogosLinuxInstaller] mv ~/Downloads/LogosLinuxInstaller\(1\) ~/Downloads/LogosLinuxInstaller
mv: overwrite '/home/thwright/Downloads/LogosLinuxInstaller'? y
(LogosLinuxInstaller) 20:19:01 [thwright@thw-g752vlw ~/Dev/LogosLinuxInstaller] LLI_CURRENT_VERSION=4.0.0-alpha.1 DIALOG=tk ./dist/LogosLinuxInstaller 
2024-04-24 20:19:12 ERROR: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Copying LogosLinuxInstaller into /home/thwright/Downloads
Installer log file: /home/thwright/.local/state/Logos_on_Linux/install.log
Logos Linux Installer, 4.0.0-alpha.1 by Ferion11, John Goodman, T. H. Wright, N. Marti.
```

Here are the logs for all my attempts today: https://pastebin.com/tK6GvnYt

**Comment by thw26** [comment]
Doh! I forgot to rebuild the binary as it replaced it. Trying again…

**Comment by thw26** [comment]
New attempt on GUI:

```
(LogosLinuxInstaller) 20:25:17 [thwright@thw-g752vlw ~/Dev/LogosLinuxInstaller] ./dist/LogosLinuxInstaller -v
Logos Linux Installer, 4.0.0-alpha.6 by Ferion11, John Goodman, T. H. Wright, N. Marti
(LogosLinuxInstaller) 20:25:22 [thwright@thw-g752vlw ~/Dev/LogosLinuxInstaller] LLI_CURRENT_VERSION=4.0.0-alpha.1 DIALOG=tk ./dist/LogosLinuxInstaller 
2024-04-24 20:25:37 CRITICAL: Could not get headers.
2024-04-24 20:25:37 ERROR: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Copying: LogosLinuxInstaller into: /home/thwright/Downloads
Exception in thread Thread-2 (update_to_latest_lli_release):
Traceback (most recent call last):
  File "threading.py", line 1073, in _bootstrap_inner
  File "threading.py", line 1010, in run
  File "utils.py", line 1643, in update_to_latest_lli_release
    update_lli_binary(app=app)
  File "utils.py", line 1424, in update_lli_binary
    logos_reuse_download(
  File "utils.py", line 593, in logos_reuse_download
    shutil.copy(os.path.join(config.MYDOWNLOADS, FILE), TARGETDIR)
  File "shutil.py", line 423, in copy
  File "shutil.py", line 260, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: '/home/thwright/Downloads/LogosLinuxInstaller'
(LogosLinuxInstaller) 20:25:57 [thwright@thw-g752vlw ~/Dev/LogosLinuxInstaller] ll ~/Downloads/LogosLinuxInstaller
ls: cannot access '/home/thwright/Downloads/LogosLinuxInstaller': No such file or directory
(LogosLinuxInstaller) 20:26:04 [thwright@thw-g752vlw ~/Dev/LogosLinuxInstaller] ll ~/Downloads/LogosLinuxInstaller
LogosLinuxInstaller(2)                LogosLinuxInstaller-3.6.3-1.sh        LogosLinuxInstaller.sh
LogosLinuxInstaller(3)                LogosLinuxInstaller.AqUmDqZH.sh.part  
(LogosLinuxInstaller) 20:26:04 [thwright@thw-g752vlw ~/Dev/LogosLinuxInstaller] mv ~/Downloads/LogosLinuxInstaller\(2\) ~/Downloads/LogosLinuxInstaller
(LogosLinuxInstaller) 20:26:42 [thwright@thw-g752vlw ~/Dev/LogosLinuxInstaller] chmod 700 ~/Downloads/LogosLinuxInstaller
(LogosLinuxInstaller) 20:26:45 [thwright@thw-g752vlw ~/Dev/LogosLinuxInstaller] ~/Downloads/LogosLinuxInstaller -v
Logos Linux Installer, 4.0.0-alpha.3 by Ferion11, John Goodman, T. H. Wright, N. Marti
(LogosLinuxInstaller) 20:26:49 [thwright@thw-g752vlw ~/Dev/LogosLinuxInstaller] LLI_CURRENT_VERSION=4.0.0-alpha.3 DIALOG=tk ./dist/LogosLinuxInstaller 
2024-04-24 20:27:07 CRITICAL: Could not get headers.
2024-04-24 20:27:07 ERROR: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
Copying: LogosLinuxInstaller into: /home/thwright/Downloads
Exception in thread Thread-2 (update_to_latest_lli_release):
Traceback (most recent call last):
  File "threading.py", line 1073, in _bootstrap_inner
  File "threading.py", line 1010, in run
  File "utils.py", line 1643, in update_to_latest_lli_release
    update_lli_binary(app=app)
  File "utils.py", line 1424, in update_lli_binary
    logos_reuse_download(
  File "utils.py", line 593, in logos_reuse_download
    shutil.copy(os.path.join(config.MYDOWNLOADS, FILE), TARGETDIR)
  File "shutil.py", line 423, in copy
  File "shutil.py", line 260, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: '/home/thwright/Downloads/LogosLinuxInstaller'
```

**Comment by n8marti** [comment]
I was able to reproduce your problem. But I figured out that it had to do with the testing setup rather than the code. If using a config file, the `LAST_UPDATED` value needs to be old enough or `null` to trigger the check for a newer version. If not, then `LOGOS_LATEST_VERSION_URL` never gets set, which is where the `None` URL error was coming from. I probably forgot to tell you that as part of my testing I was backdating the `LAST_UPDATED` by a couple of days.

On the other hand, I now see that the download progress doesn't display properly, so I want to look at that next.

**Comment by n8marti** [comment]
Okay, go ahead and test again. I these are all the steps I've been using:
- make sure LogosLinuxInstaller in Downloads is not latest version (optionally make a backup for retesting)
- make sure LAST_UPDATE in the config file is `null` or backdated so that the update check runs
- build the binary locally (optionally make a backup for retesting)
- run with `LLI_CURRENT_VERSION=4.0.0-alpha.1 DIALOG=tk ./dist/LogosLinuxInstaller -D`
- click "Update" button to run the actual test

**Comment by thw26** [comment]
Retested. GUI works. Binary is deleted, downloaded, but not made executable in Downloads.

**Comment by thw26** [comment]
When I launch the app, the title is so long that the middle is replaced with an ellipsis.

I only see the ext:

```
FaithLife Bib....0.0-alpha.6
```

The panel does not allow me to resize it.

**Comment by n8marti** [comment]
How about something like this?
image

**Pull request merged**
